### ISSUE TITLE
pytest-splinter hangs on travis

### ISSUE THREAD

**Issue by davidemoro** [pytest-dev/pytest-splinter#71]
Hi,

I'm migrating a package from `pytest-selenium` to `pytest-splinter`.
This package provides a scaffolding tool that let you clone an existing package named `tierra_qa` from `whateveryouwant_qa`. See:
- https://travis-ci.org/tierratelematics/tierra_qa/builds/154694705

Tests on on the fresh clone goes fine locally but on travisCI the process hangs.

Do you have any tip about why? Don't know, probably it depends on the different way pytest-splinter manages the browser lifecycle?

Thanks in advance

**Comment by bubenkoff** [comment]
Hi, does it start xvfb? it should, otherwise it will behave like that i think
check how the tests of pytest-splinter work

**Comment by eisensheng** [comment]
I'm also affected by hangs in pytest-splinter. Unfortunately I can't really point it down to something specific. For what it's worth, I'm using latest ArchLinux with all updates installed and Python3.5. 

The given test suite as simple as
```python
import time

import pytest


@pytest.fixture()
def splinter_webdriver():
    return 'chrome'


def test_visit_google(browser):
    browser.visit('https://www.google.de/')
    time.sleep(200)
```

fails to run. A Chromium window appears and almost immediately disappears again for several times until I get impatient and hit ^C. Phantomjs hangs forever too. This was tested in a fresh and clean virtualenv with the master branch of pytest-splinter.

The traceback here isn't helpful either. It's filled with messages

```
Traceback (most recent call last):
  File ".../src/pytest-splinter/pytest_splinter/plugin.py", line 410, in prepare_browser
    browser.driver.set_window_size(*splinter_window_size)
  File ".../lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 846, in set_window_size
    'windowHandle': windowHandle})
  File ".../src/pytest-splinter/pytest_splinter/webdriver_patches.py", line 56, in execute
    result = self._base_execute(driver_command, params)
  File ".../lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File ".../lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: No current window
JavaScript stack:
Error: No current window
    at checkForExtensionError (chrome-extension://aapnijgdinlhnhlmodcfapnahmbfebeb/background.js:14:17)
    at null.callback (chrome-extension://aapnijgdinlhnhlmodcfapnahmbfebeb/background.js:67:5)
    at safeCallbackApply (extensions::sendRequest:21:15)
    at handleResponse (extensions::sendRequest:74:7)
  (Session info: chrome=52.0.2743.116)
  (Driver info: chromedriver=2.21,platform=Linux 4.7.2-1-ARCH x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".../src/pytest-splinter/pytest_splinter/plugin.py", line 410, in prepare_browser
    browser.driver.set_window_size(*splinter_window_size)
  File ".../lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 846, in set_window_size
    'windowHandle': windowHandle})
  File ".../src/pytest-splinter/pytest_splinter/webdriver_patches.py", line 56, in execute
    result = self._base_execute(driver_command, params)
  File ".../lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File ".../lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: No current window
JavaScript stack:
Error: No current window
    at checkForExtensionError (chrome-extension://aapnijgdinlhnhlmodcfapnahmbfebeb/background.js:14:17)
    at null.callback (chrome-extension://aapnijgdinlhnhlmodcfapnahmbfebeb/background.js:67:5)
    at safeCallbackApply (extensions::sendRequest:21:15)
    at handleResponse (extensions::sendRequest:74:7)
  (Session info: chrome=52.0.2743.116)
  (Driver info: chromedriver=2.21,platform=Linux 4.7.2-1-ARCH x86_64)

---8<--- even more trash ---8<---

  File ".../src/pytest-splinter/pytest_splinter/plugin.py", line 426, in prepare_browser
    prepare_browser(request, parent)
  File ".../src/pytest-splinter/pytest_splinter/plugin.py", line 426, in prepare_browser
    prepare_browser(request, parent)
  File ".../src/pytest-splinter/pytest_splinter/plugin.py", line 426, in prepare_browser
    prepare_browser(request, parent)
  File ".../src/pytest-splinter/pytest_splinter/plugin.py", line 426, in prepare_browser
    prepare_browser(request, parent)
  File ".../src/pytest-splinter/pytest_splinter/plugin.py", line 426, in prepare_browser
    prepare_browser(request, parent)
  File ".../src/pytest-splinter/pytest_splinter/plugin.py", line 425, in prepare_browser
    browser = browser_pool[browser_key] = get_browser(splinter_webdriver)
  File ".../src/pytest-splinter/pytest_splinter/plugin.py", line 381, in get_browser
    wait_time=splinter_wait_time, **kwargs
  File ".../src/pytest-splinter/pytest_splinter/plugin.py", line 68, in Browser
    browser = splinter.Browser(*args, **kwargs)
  File ".../lib/python3.5/site-packages/splinter/browser.py", line 63, in Browser
    return driver(*args, **kwargs)
  File ".../lib/python3.5/site-packages/splinter/driver/webdriver/chrome.py", line 31, in __init__
    self.driver = Chrome(chrome_options=options, **kwargs)
  File ".../lib/python3.5/site-packages/selenium/webdriver/chrome/webdriver.py", line 62, in __init__
    self.service.start()
  File ".../lib/python3.5/site-packages/selenium/webdriver/common/service.py", line 90, in start
    time.sleep(1)
KeyboardInterrupt
```

Using splinter directly works though
```python
from splinter import Browser

with Browser('chrome') as browser:
    # Visit URL
    url = "http://www.google.com"
    browser.visit(url)
    browser.fill(
        'q', 'splinter - python acceptance testing for web applications')
    # Find and click the 'search' button
    button = browser.find_by_name('btnG')
    # Interact with elements
    button.click()
    if browser.is_text_present('splinter.readthedocs.io'):
        print("Yes, the official website was found!")
    else:
        print("No, it wasn't found... We need to improve our SEO techniques")
```

**Comment by bubenkoff** [comment]
so in the same virtualenv, using clean splinter it just works?

**Comment by eisensheng** [comment]
> so in the same virtualenv, using clean splinter it just works?

Yes. 

Nevermind the phantomjs part though. It seems that I was just a little bit too impatient, it just takes some time when started by py.test-splinter. 

Using Chromium still gives me the odd the odd behavior though. I was able to pin it down through running the chromedriver in another terminal and inspecting the log output. Most interesting line was:

```
[2,241][INFO]: RESPONSE SetWindowSize unknown error: No current window
JavaScript stack:
Error: No current window
    at checkForExtensionError (chrome-extension://aapnijgdinlhnhlmodcfapnahmbfebeb/background.js:14:17)
    at null.callback (chrome-extension://aapnijgdinlhnhlmodcfapnahmbfebeb/background.js:67:5)
    at safeCallbackApply (extensions::sendRequest:21:15)
    at handleResponse (extensions::sendRequest:74:7)
  (Session info: chrome=52.0.2743.116)
```

So I added 
```python
@pytest.fixture(scope='session')
def splinter_window_size():
    return None
```

to the test file and suddenly it (almost) works. The chrome driver only hangs during the Quit command now for like ~30 seconds. But the test passes! :confetti_ball:

**Comment by davidemoro** [comment]
Hi @bubenkoff,

yes: xvfb is started.
I'll have a deeper look at pytest-splinter time. Only travis builds are affected, could it hangs like that because of a missing environment variable in your experience?

**Comment by pelme** [comment]
This issue has also been reported in #72 and #73.

The issue seems to be that calling `set_window_size()` causes Chrome to raise a `WebDriverException`. In combination with prepare_browser retrying indefinately on`WebDriverException`s (see https://github.com/pytest-dev/pytest-splinter/blob/f0376e4179a4263feca8d2a63b505fafc4dff557/pytest_splinter/plugin.py#L419) this leads to infinite browser start/crash/restart cycles.

**Comment by aaugustin** [comment]
My workaround:

```python
# conftest.py

@pytest.fixture(scope='session')
def splinter_window_size(splinter_webdriver, splinter_window_size):
    """
    Prevent pytest-splinter from crashing with Chrome.

    """
    if splinter_webdriver == 'chrome':
        return None

    return splinter_window_size
```
